# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Visual Studio Enterprise Subscription (1ceaf434-2986-4ab6-86c7-20fa012fef90)'
    subscriptionId: '1ceaf434-2986-4ab6-86c7-20fa012fef90'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'Intellipaat'
    location: 'East US'
    templateLocation: 'Linked artifact'
    csmFile: 'main.bicep'
    csmParametersFile: 'parameters.bicepparam'
    deploymentMode: 'Incremental'
