# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

name: Deploy Bicep files

pool:
  vmImage: ubuntu-latest

parameters:
- name: azureServiceConnection
  type: string
  default: '1ceaf434-2986-4ab6-86c7-20fa012fef90'

variables:
  vmImageName: 'ubuntu-latest'
  resourceGroupName: 'Intellipaat'
  location: 'eastus'
  templateFile: './main.bicep'
  csmParametersFile: './parameters.bicepparam'

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureSubscription: '${{ parameters.azureServiceConnection }}'
    action: 'Create Or Update Resource Group'
    resourceGroupName: '$(resourceGroupName)'
    location: '$(location)'
    templateLocation: 'Linked artifact'
    csmFile: '$(templateFile)'
    csmParametersFile: '$(csmParametersFile)'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'
