apiVersion: v1
kind: Service
metadata:
    name: intellipaatpythonapp
spec:
    type: LoadBalancer
    ports:
    - port: 80
    - targetPort: 5000
    selector:
        app: intellipaatpythonapp